<<<<<<< HEAD
name = "sctec"
compatibility_date = "2026-01-11"

[assets]
directory = "."
=======

name = "sctec"
type = "webpack"

[build]
command = "npm run build"

[assets]
directory = "."


>>>>>>> aa9b59b2df0040de46e1c0767a044faa5c723257


